services:
  database:
    shm_size: 128mb
    environment:
      DTOCEAN_DB_EXAMPLES_NAME: ${DTOCEAN_DB_EXAMPLES_NAME:-dtocean_examples}
      DTOCEAN_DB_TEMPLATE_NAME: ${DTOCEAN_DB_TEMPLATE_NAME:-dtocean_template}
      DTOCEAN_DB_VERSION: ${DTOCEAN_DB_VERSION}
      DTOCEAN_USER_NAME: ${DTOCEAN_USER_NAME:-dtocean_user}
      DTOCEAN_USER_PASSWORD: ${DTOCEAN_USER_PASSWORD:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  pgadmin:
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_DEFAULT_EMAIL: dtocean@example.com
      PGADMIN_DEFAULT_PASSWORD: ${DTOCEAN_USER_PASSWORD:?}
    ports:
      - ${PGADMIN_PORT:-8080}:80
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

configs:
  pgpass:
    content: "db:5432:*:postgres:${POSTGRES_PASSWORD:?}"
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "dtocean",
        "Host": "database",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "postgres",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}
