services:
  database:
    build:
      context: postgresql
      dockerfile: Dockerfile
    volumes:
      - ./export:/home/postgres/export
      - db-data:/var/lib/postgresql/data
    
  pgadmin:
    build:
      context: pgadmin4
      dockerfile: Dockerfile
    volumes:
      - ./export:/home/pgadmin/export

volumes:
  db-data:
